"""empty message

Revision ID: 06a3995bdb12
Revises: 1b396063a99f
Create Date: 2022-04-20 09:07:35.012230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a3995bdb12'
down_revision = '1b396063a99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_group', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_group', 'is_admin')
    # ### end Alembic commands ###
