"""empty message

Revision ID: 110581c8d93e
Revises: 42d7f0de9e43
Create Date: 2022-03-25 18:05:46.363776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '110581c8d93e'
down_revision = '42d7f0de9e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('finalized', sa.Boolean(), nullable=True))
    op.drop_column('events', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FINALIZED', name='event_statuses'), autoincrement=False, nullable=True))
    op.drop_column('events', 'finalized')
    # ### end Alembic commands ###
