"""empty message

Revision ID: 1c948d60dbaf
Revises: 
Create Date: 2022-04-01 14:52:16.366743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c948d60dbaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_timeblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeblock_id', sa.Integer(), nullable=True),
    sa.Column('invitation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['timeblock_id'], ['timeblocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('finalized', sa.Boolean(), nullable=True))
    op.add_column('invitations', sa.Column('finalized', sa.Boolean(), nullable=True))
    op.add_column('timeblocks', sa.Column('is_conflict', sa.Boolean(), nullable=True))
    op.add_column('timeblocks', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timeblocks', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeblocks', type_='foreignkey')
    op.drop_column('timeblocks', 'event_id')
    op.drop_column('timeblocks', 'is_conflict')
    op.drop_column('invitations', 'finalized')
    op.drop_column('events', 'finalized')
    op.drop_table('invitation_timeblock')
    # ### end Alembic commands ###
