"""empty message

Revision ID: 1fb98170521f
Revises: 8fd1e72cc6cd
Create Date: 2022-03-19 23:01:55.373339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb98170521f'
down_revision = '8fd1e72cc6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('netid', sa.String(length=64), nullable=True))
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['netid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.drop_column('users', 'netid')
    # ### end Alembic commands ###
