"""empty message

Revision ID: 42d7f0de9e43
Revises: 1fb98170521f
Create Date: 2022-03-25 17:50:22.396438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '42d7f0de9e43'
down_revision = '1fb98170521f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands generated by lu:
    event_statuses = postgresql.ENUM('PENDING', 'SENT', 'FINALIZED', name='event_statuses')
    event_statuses.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.Enum('PENDING', 'SENT', 'FINALIZED', name='event_statuses'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    # ### end Alembic commands ###

    # ### commands generated by lu:
    event_statuses = postgresql.ENUM('PENDING', 'SENT', 'FINALIZED', name='event_statuses')
    event_statuses.drop(op.get_bind())
