"""empty message

Revision ID: 46e58e546840
Revises: c39bd3be817e
Create Date: 2022-04-25 17:50:47.987170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e58e546840'
down_revision = 'c39bd3be817e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_recurring')
    # ### end Alembic commands ###
