"""empty message

Revision ID: 8fd1e72cc6cd
Revises: dc86747fd240
Create Date: 2022-03-19 22:52:21.282980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd1e72cc6cd'
down_revision = 'dc86747fd240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_netid_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'netid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('netid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_netid_key', 'users', ['netid'])
    # ### end Alembic commands ###
