"""empty message

Revision ID: aadb325b1c4b
Revises: 51bc4004a7c3
Create Date: 2022-04-28 12:02:04.746844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadb325b1c4b'
down_revision = '51bc4004a7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
