"""empty message

Revision ID: f83c9349cf91
Revises: 110581c8d93e
Create Date: 2022-03-25 18:14:13.371863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83c9349cf91'
down_revision = '110581c8d93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('finalized', sa.Boolean(), nullable=True))
    op.add_column('timeblocks', sa.Column('is_conflict', sa.Boolean(), nullable=True))
    op.add_column('timeblocks', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timeblocks', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeblocks', type_='foreignkey')
    op.drop_column('timeblocks', 'event_id')
    op.drop_column('timeblocks', 'is_conflict')
    op.drop_column('invitations', 'finalized')
    # ### end Alembic commands ###
